// <auto-generated />
using System;
using EvalRight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvalRight.Infrastructure.Migrations
{
    [DbContext(typeof(EvalRightDbContext))]
    [Migration("20251213150731_AddEmailPhoneToClient")]
    partial class AddEmailPhoneToClient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EvalRight.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.AccountRole", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeType")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ScopeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("AssignedById")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId", "RoleId", "ScopeType", "ScopeId");

                    b.HasIndex("AssignedById");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("ActorAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.AuthSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AuthSessions");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvComponentsCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultRegion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DefaultTurnaroundDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SupportsMultipleInstances")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BgvComponentsCatalog");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BgvRegion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientBranchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("InitiatedByAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("PackageId")
                        .HasColumnType("bigint");

                    b.Property<string>("PricingSnapshotJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ClientId");

                    b.HasIndex("InitiatedByAccountId");

                    b.HasIndex("PackageId");

                    b.ToTable("BgvOrders");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvOrderComponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ComponentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstanceIndex")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastStatusChangeAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawInputJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RawResultJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("BgvOrderId", "ComponentId", "InstanceIndex")
                        .IsUnique();

                    b.ToTable("BgvOrderComponents");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvOrderEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedByAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EventSource")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BgvOrderId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BgvOrderEvents");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegionScope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BgvPackages");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvPackageComponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ComponentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("PackageId", "ComponentId")
                        .IsUnique();

                    b.ToTable("BgvPackageComponents");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BillingCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DefaultPaymentMethodId")
                        .HasColumnType("bigint");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("BillingCustomers");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BillingOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PricingSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BgvOrderId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.ToTable("BillingOrders");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BillingPaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BillingCustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int?>("ExpYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Last4")
                        .HasColumnType("longtext");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingCustomerId");

                    b.ToTable("BillingPaymentMethods");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateAddresses");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ApprovedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MimeType")
                        .HasColumnType("longtext");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UploadedByAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BgvOrderId");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateDocuments");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateDocumentRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RequirementId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("WaivedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("WaivedReason")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BgvOrderId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("CandidateId", "BgvOrderId", "RequirementId")
                        .IsUnique();

                    b.ToTable("CandidateDocumentRequirements");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateEducation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Degree")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Major")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateEducations");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateEmployment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateEmployments");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InvitedPhone")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("InvitationToken")
                        .IsUnique();

                    b.ToTable("CandidateInvitations");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateProfileData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "TaskCode")
                        .IsUnique();

                    b.ToTable("CandidateProfileData");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateTaskStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EditableByCandidate")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("EditableUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedByAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "BgvOrderId", "TaskCode")
                        .IsUnique();

                    b.ToTable("CandidateTaskStatuses");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateTimelineEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BgvOrderId");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateTimelineEvents");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("AutopayEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BillingMode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("ClientGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Industry")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("SignupDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TaxExemptionDetails")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientGroupId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientBranch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientBranches");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPrimaryBilling")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrimaryTechnical")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientContacts");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClientGroups");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientPackageOverride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomDisplayName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OverridePricingJson")
                        .HasColumnType("longtext");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "PackageId")
                        .IsUnique();

                    b.ToTable("ClientPackageOverrides");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientRegistrationForm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AgreedName")
                        .HasColumnType("longtext");

                    b.Property<string>("AgreedTitle")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("AgreedTosAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("longtext");

                    b.Property<long?>("ReviewedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("SubmittedByAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("SubmittedByAccountId");

                    b.ToTable("ClientRegistrationForms");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("AllowALaCarteComponents")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BusinessType")
                        .HasColumnType("longtext");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultRegion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InviteExpiryDays")
                        .HasColumnType("int");

                    b.Property<string>("PermissiblePurpose")
                        .HasColumnType("longtext");

                    b.Property<bool>("RequireCandidateConsent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ClientSettings");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientTransactions");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.DocumentRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instructions")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxCount")
                        .HasColumnType("int");

                    b.Property<int>("MinCount")
                        .HasColumnType("int");

                    b.Property<long?>("PackageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("PackageId");

                    b.ToTable("DocumentRequirements");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.IdaCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BgvOrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdaCandidateId")
                        .HasColumnType("longtext");

                    b.Property<string>("IdaCaseReference")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("LastWebhookAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OverallStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("RawLastPayload")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BgvOrderId")
                        .IsUnique();

                    b.ToTable("IdaCases");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.IdaCaseComponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdaCaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdaComponentId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LastStatusChangeAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdaCaseId");

                    b.ToTable("IdaCaseComponents");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.IdaJobRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdaJobRoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdaJobRoleName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "IdaJobRoleId")
                        .IsUnique();

                    b.ToTable("IdaJobRoles");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("AutopayAttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AutopayLastError")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("BillingPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("BillingPeriodStart")
                        .HasColumnType("date");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StripeInvoiceId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long?>("BillingOrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingOrderId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLineItems");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.InvoicePayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<long?>("RecordedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StripeChargeId")
                        .HasColumnType("longtext");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.JobQueue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastError")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("JobQueue");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.UserProfile", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Locale")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Timezone")
                        .HasColumnType("longtext");

                    b.HasKey("AccountId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalReferenceIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadRaw")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("RelatedCandidateId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelatedOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestPath")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedCandidateId");

                    b.HasIndex("RelatedOrderId");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.AccountRole", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvalRight.Domain.Entities.Account", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EvalRight.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AssignedBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.AuthSession", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Account", "Account")
                        .WithMany("AuthSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvOrder", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvalRight.Domain.Entities.Account", "InitiatedByAccount")
                        .WithMany()
                        .HasForeignKey("InitiatedByAccountId");

                    b.HasOne("EvalRight.Domain.Entities.BgvPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.Navigation("Candidate");

                    b.Navigation("Client");

                    b.Navigation("InitiatedByAccount");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvOrderComponent", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "BgvOrder")
                        .WithMany("Components")
                        .HasForeignKey("BgvOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvalRight.Domain.Entities.BgvComponentsCatalog", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BgvOrder");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvOrderEvent", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "BgvOrder")
                        .WithMany("Events")
                        .HasForeignKey("BgvOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvalRight.Domain.Entities.BgvComponentsCatalog", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.Navigation("BgvOrder");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvPackageComponent", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvComponentsCatalog", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvalRight.Domain.Entities.BgvPackage", "Package")
                        .WithMany("PackageComponents")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BillingCustomer", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BillingOrder", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "BgvOrder")
                        .WithMany()
                        .HasForeignKey("BgvOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BgvOrder");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BillingPaymentMethod", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BillingCustomer", "BillingCustomer")
                        .WithMany()
                        .HasForeignKey("BillingCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingCustomer");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateAddress", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Addresses")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateDocument", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "BgvOrder")
                        .WithMany()
                        .HasForeignKey("BgvOrderId");

                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BgvOrder");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateDocumentRequirement", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "BgvOrder")
                        .WithMany()
                        .HasForeignKey("BgvOrderId");

                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvalRight.Domain.Entities.DocumentRequirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BgvOrder");

                    b.Navigation("Candidate");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateEducation", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateEmployment", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Employments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateInvitation", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateProfileData", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateTaskStatus", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.CandidateTimelineEvent", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "BgvOrder")
                        .WithMany()
                        .HasForeignKey("BgvOrderId");

                    b.HasOne("EvalRight.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BgvOrder");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Client", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.ClientGroup", "ClientGroup")
                        .WithMany()
                        .HasForeignKey("ClientGroupId");

                    b.Navigation("ClientGroup");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientBranch", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany("Branches")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientContact", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientPackageOverride", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientRegistrationForm", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("EvalRight.Domain.Entities.Account", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId");

                    b.HasOne("EvalRight.Domain.Entities.Account", "SubmittedByAccount")
                        .WithMany()
                        .HasForeignKey("SubmittedByAccountId");

                    b.Navigation("Client");

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("SubmittedByAccount");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientSettings", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithOne("Settings")
                        .HasForeignKey("EvalRight.Domain.Entities.ClientSettings", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.ClientTransaction", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.DocumentRequirement", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvComponentsCatalog", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.HasOne("EvalRight.Domain.Entities.BgvPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.Navigation("Component");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.IdaCase", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "BgvOrder")
                        .WithMany()
                        .HasForeignKey("BgvOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BgvOrder");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.IdaCaseComponent", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.IdaCase", "IdaCase")
                        .WithMany("Components")
                        .HasForeignKey("IdaCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdaCase");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.IdaJobRole", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BgvPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.BillingOrder", "BillingOrder")
                        .WithMany()
                        .HasForeignKey("BillingOrderId");

                    b.HasOne("EvalRight.Domain.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingOrder");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.InvoicePayment", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("EvalRight.Domain.Entities.UserProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.WebhookEvent", b =>
                {
                    b.HasOne("EvalRight.Domain.Entities.Candidate", "RelatedCandidate")
                        .WithMany()
                        .HasForeignKey("RelatedCandidateId");

                    b.HasOne("EvalRight.Domain.Entities.BgvOrder", "RelatedOrder")
                        .WithMany()
                        .HasForeignKey("RelatedOrderId");

                    b.Navigation("RelatedCandidate");

                    b.Navigation("RelatedOrder");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("AuthSessions");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvOrder", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.BgvPackage", b =>
                {
                    b.Navigation("PackageComponents");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Educations");

                    b.Navigation("Employments");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Client", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Contacts");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.IdaCase", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("EvalRight.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
